### ISSUE TITLE
Why ins't this avaliable for Godot 3?

### ISSUE THREAD

**Issue by Axis4s** [MenacingMecha/godot-n64-shader-demo#3]
_

**Comment by MenacingMecha** [comment]
Hi, it is, check the [v1.x branch](https://github.com/MenacingMecha/godot-n64-shader-demo/tree/v1.x) and the [latest v1 release](https://github.com/MenacingMecha/godot-n64-shader-demo/releases/tag/v1.0.3).

I see now that this is poorly communicated in the README, and should be updated to make it clearer.
